In [1]:
import numpy as np
import pandas as pd

In [24]:
order_details = pd.read_csv("order_details.csv")
order_details

       order_details_id  order_id       pizza_id  quantity
0                     1         1     hawaiian_m         1
1                     2         2  classic_dlx_m         1
2                     3         2  five_cheese_l         1
3                     4         2    ital_supr_l         1
4                     5         2     mexicana_m         1
...                 ...       ...            ...       ...
48615             48616     21348  ckn_alfredo_m         1
48616             48617     21348  four_cheese_l         1
48617             48618     21348   napolitana_s         1
48618             48619     21349     mexicana_l         1
48619             48620     21350      bbq_ckn_s         1

[48620 rows x 4 columns]

In [3]:
order_details.shape

(48620, 4)

In [4]:
order_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [5]:
order_details.columns

Index(['order_details_id', 'order_id', 'pizza_id', 'quantity'], dtype='object')

In [6]:
order_details.isna().sum()

order_details_id    0
order_id            0
pizza_id            0
quantity            0
dtype: int64

In [7]:
order = pd.read_csv("orders.csv")
order

       order_id        date      time
0             1  2015-01-01  11:38:36
1             2  2015-01-01  11:57:40
2             3  2015-01-01  12:12:28
3             4  2015-01-01  12:16:31
4             5  2015-01-01  12:21:30
...         ...         ...       ...
21345     21346  2015-12-31  20:51:07
21346     21347  2015-12-31  21:14:37
21347     21348  2015-12-31  21:23:10
21348     21349  2015-12-31  22:09:54
21349     21350  2015-12-31  23:02:05

[21350 rows x 3 columns]

In [8]:
order.shape

(21350, 3)

In [9]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  21350 non-null  int64
 1   date      21350 non-null  object
 2   time      21350 non-null  object
dtypes: int64(1), object(2)
memory usage: 500.5+ KB

In [10]:
order.columns

Index(['order_id', 'date', 'time'], dtype='object')

In [11]:
order.isna().sum()

order_id    0
date        0
time        0
dtype: int64

In [12]:
order.duplicated().sum()

np.int64(0)

In [13]:
pizzas = pd.read_csv("pizzas.csv")
pizzas

         pizza_id pizza_type_id size  price
0       bbq_ckn_s       bbq_ckn    S  12.75
1       bbq_ckn_m       bbq_ckn    M  16.75
2       bbq_ckn_l       bbq_ckn    L  20.75
3      cali_ckn_s      cali_ckn    S  12.75
4      cali_ckn_m      cali_ckn    M  16.75
..            ...           ...  ...    ...
91  spinach_fet_m   spinach_fet    M  16.00
92  spinach_fet_l   spinach_fet    L  20.25
93   veggie_veg_s    veggie_veg    S  12.00
94   veggie_veg_m    veggie_veg    M  16.00
95   veggie_veg_l    veggie_veg    L  20.25

[96 rows x 4 columns]

In [14]:
pizzas.shape

(96, 4)

In [15]:
pizzas.info

<bound method DataFrame.info of          pizza_id pizza_type_id size  price
0       bbq_ckn_s       bbq_ckn    S  12.75
1       bbq_ckn_m       bbq_ckn    M  16.75
2       bbq_ckn_l       bbq_ckn    L  20.75
3      cali_ckn_s      cali_ckn    S  12.75
4      cali_ckn_m      cali_ckn    M  16.75
..            ...           ...  ...    ...
91  spinach_fet_m   spinach_fet    M  16.00
92  spinach_fet_l   spinach_fet    L  20.25
93   veggie_veg_s    veggie_veg    S  12.00
94   veggie_veg_m    veggie_veg    M  16.00
95   veggie_veg_l    veggie_veg    L  20.25

[96 rows x 4 columns]>

In [16]:
pizzas.columns

Index(['pizza_id', 'pizza_type_id', 'size', 'price'], dtype='object')

In [17]:
pizzas.isna().sum()

pizza_id         0
pizza_type_id    0
size             0
price            0
dtype: int64

In [18]:
pizzas.duplicated().sum()

np.int64(0)

In [19]:
pizzas_types= pd.read_csv("pizza_types_d.csv", encoding="latin1")
pizzas_types

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
3,ckn_pesto,The Chicken Pesto Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
4,southw_ckn,The Southwest Chicken Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."
5,thai_ckn,The Thai Chicken Pizza,Chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha..."
6,big_meat,The Big Meat Pizza,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
7,classic_dlx,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
8,hawaiian,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
9,ital_cpcllo,The Italian Capocollo Pizza,Classic,"Capocollo, Red Peppers, Tomatoes, Goat Cheese,..."
10,napolitana,The Napolitana Pizza,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,..."
11,pep_msh_pep,"The Pepperoni, Mushroom, and Peppers Pizza",Classic,"Pepperoni, Mushrooms, Green Peppers"
12,pepperoni,The Pepperoni Pizza,Classic,"Mozzarella Cheese, Pepperoni"
13,the_greek,The Greek Pizza,Classic,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic..."
14,brie_carre,The Brie Carre Pizza,Supreme,"Brie Carre Cheese, Prosciutto, Caramelized Oni..."
15,calabrese,The Calabrese Pizza,Supreme,"Nduja Salami, Pancetta, Tomatoes, Red Onions,..."
16,ital_supr,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
17,peppr_salami,The Pepper Salami Pizza,Supreme,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ..."
18,prsc_argla,The Prosciutto and Arugula Pizza,Supreme,"Prosciutto di San Daniele, Arugula, Mozzarella..."
19,sicilian,The Sicilian Pizza,Supreme,"Coarse Sicilian Salami, Tomatoes, Green Olives..."
20,soppressata,The Soppressata Pizza,Supreme,"Soppressata Salami, Fontina Cheese, Mozzarella..."
21,spicy_ital,The Spicy Italian Pizza,Supreme,"Capocollo, Tomatoes, Goat Cheese, Artichokes, ..."
22,spinach_supr,The Spinach Supreme Pizza,Supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti..."
23,five_cheese,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go..."
24,four_cheese,The Four Cheese Pizza,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo..."
25,green_garden,The Green Garden Pizza,Veggie,"Spinach, Mushrooms, Tomatoes, Green Olives, Fe..."
26,ital_veggie,The Italian Vegetables Pizza,Veggie,"Eggplant, Artichokes, Tomatoes, Zucchini, Red ..."
27,mediterraneo,The Mediterranean Pizza,Veggie,"Spinach, Artichokes, Kalamata Olives, Sun-drie..."
28,mexicana,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
29,spin_pesto,The Spinach Pesto Pizza,Veggie,"Spinach, Artichokes, Tomatoes, Sun-dried Tomat..."
30,spinach_fet,The Spinach and Feta Pizza,Veggie,"Spinach, Mushrooms, Red Onions, Feta Cheese, G..."
31,veggie_veg,The Vegetables + Vegetables Pizza,Veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."

In [20]:
pizzas_types.shape

(32, 4)

In [21]:
pizzas_types.info

<bound method DataFrame.info of    pizza_type_id                                        name category  \
0        bbq_ckn                  The Barbecue Chicken Pizza  Chicken
1       cali_ckn                The California Chicken Pizza  Chicken
2    ckn_alfredo                   The Chicken Alfredo Pizza  Chicken
3      ckn_pesto                     The Chicken Pesto Pizza  Chicken
4     southw_ckn                 The Southwest Chicken Pizza  Chicken
5       thai_ckn                      The Thai Chicken Pizza  Chicken
6       big_meat                          The Big Meat Pizza  Classic
7    classic_dlx                    The Classic Deluxe Pizza  Classic
8       hawaiian                          The Hawaiian Pizza  Classic
9    ital_cpcllo                 The Italian Capocollo Pizza  Classic
10    napolitana                        The Napolitana Pizza  Classic
11   pep_msh_pep  The Pepperoni, Mushroom, and Peppers Pizza  Classic
12     pepperoni                         The Pepperoni Pizza  Classic
13     the_greek                             The Greek Pizza  Classic
14    brie_carre                        The Brie Carre Pizza  Supreme
15     calabrese                         The Calabrese Pizza  Supreme
16     ital_supr                   The Italian Supreme Pizza  Supreme
17  peppr_salami                     The Pepper Salami Pizza  Supreme
18    prsc_argla            The Prosciutto and Arugula Pizza  Supreme
19      sicilian                          The Sicilian Pizza  Supreme
20   soppressata                       The Soppressata Pizza  Supreme
21    spicy_ital                     The Spicy Italian Pizza  Supreme
22  spinach_supr                   The Spinach Supreme Pizza  Supreme
23   five_cheese                       The Five Cheese Pizza   Veggie
24   four_cheese                       The Four Cheese Pizza   Veggie
25  green_garden                      The Green Garden Pizza   Veggie
26   ital_veggie                The Italian Vegetables Pizza   Veggie
27  mediterraneo                     The Mediterranean Pizza   Veggie
28      mexicana                          The Mexicana Pizza   Veggie
29    spin_pesto                     The Spinach Pesto Pizza   Veggie
30   spinach_fet                  The Spinach and Feta Pizza   Veggie
31    veggie_veg           The Vegetables + Vegetables Pizza   Veggie

                                          ingredients
0   Barbecued Chicken, Red Peppers, Green Peppers,...
1   Chicken, Artichoke, Spinach, Garlic, Jalapeno ...
2   Chicken, Red Onions, Red Peppers, Mushrooms, A...
3   Chicken, Tomatoes, Red Peppers, Spinach, Garli...
4   Chicken, Tomatoes, Red Peppers, Red Onions, Ja...
5   Chicken, Pineapple, Tomatoes, Red Peppers, Tha...
6   Bacon, Pepperoni, Italian Sausage, Chorizo Sau...
7   Pepperoni, Mushrooms, Red Onions, Red Peppers,...
8            Sliced Ham, Pineapple, Mozzarella Cheese
9   Capocollo, Red Peppers, Tomatoes, Goat Cheese,...
10  Tomatoes, Anchovies, Green Olives, Red Onions,...
11                Pepperoni, Mushrooms, Green Peppers
12                       Mozzarella Cheese, Pepperoni
13  Kalamata Olives, Feta Cheese, Tomatoes, Garlic...
14  Brie Carre Cheese, Prosciutto, Caramelized Oni...
15  Nduja Salami, Pancetta, Tomatoes, Red Onions,...
16  Calabrese Salami, Capocollo, Tomatoes, Red Oni...
17  Genoa Salami, Capocollo, Pepperoni, Tomatoes, ...
18  Prosciutto di San Daniele, Arugula, Mozzarella...
19  Coarse Sicilian Salami, Tomatoes, Green Olives...
20  Soppressata Salami, Fontina Cheese, Mozzarella...
21  Capocollo, Tomatoes, Goat Cheese, Artichokes, ...
22  Spinach, Red Onions, Pepperoni, Tomatoes, Arti...
23  Mozzarella Cheese, Provolone Cheese, Smoked Go...
24  Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...
25  Spinach, Mushrooms, Tomatoes, Green Olives, Fe...
26  Eggplant, Artichokes, Tomatoes, Zucchini, Red ...
27  Spinach, Artichokes, Kalamata Olives, Sun-drie...
28  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...
29  Spinach, Artichokes, Tomatoes, Sun-dried Tomat...
30  Spinach, Mushrooms, Red Onions, Feta Cheese, G...
31  Mushrooms, Tomatoes, Red Peppers, Green Pepper...  >

In [22]:
pizzas_types.isna().sum()

pizza_type_id    0
name             0
category         0
ingredients      0
dtype: int64

after checking the details about all the dataset all are clearned so we move merge

# Merge the  Necesary  Dataset

In [23]:
df = order_detail.merge(pizzas, on="pizza_id")
df

NameError: name 'order_detail' is not defined

In [ ]:
df["revenue"] = df["quantity"] * df["price"]
df

Question (1),  To calculate the tolal revenue

In [ ]:
total_revenue = df["revenue"].sum()
print("Total Revenue \n:", "$", total_revenue)

Question (2),  Calculate the total quantity

In [ ]:
total_quantity = order_details["quantity"].sum()
print("Total Quantity  \n:", total_quantity)

Question (3), Find the total number of orders

In [ ]:
total_orders = order["order_id"].nunique()
print("Total Order \n:", total_orders)

Question (4), How many pizza types do they sell

In [ ]:
total_pizza_types = pizzas_types["name"].nunique()
print("Total Pizzas By Name \n:", total_pizza_types)

Question (5), find the avg price of the pizzas

In [ ]:
avg_pizzas = pizzas["price"].mean()
print("Avg Pizzas Price \n", "$", avg_pizzas)

Question (6), what are the peak hours of sales

In [ ]:
df = order.merge(order_details, on ="order_id")
df

df = df.merge(pizzas, on= "pizza_id")
df

In [ ]:
df["revenue"]= df["quantity"] * df["price"]

In [ ]:
df["hour"] = pd.to_datetime(df["time"]).dt.hour
df

In [ ]:
hourly_sales= df.groupby("hour")["revenue"].sum()
print(hourly_sales)

In [ ]:
peak_hour = hourly_sales.idxmax()
peak_sales = hourly_sales.max()

print(f"Peak Hour: {peak_hour}:00")
print(f"Sales: ${peak_sales}")

Qeustion (7), Find the total sales made on each day of the week. Which day of the week is when sales
are made the most

In [ ]:
df["date"] = pd.to_datetime(df["date"])

In [ ]:
df["day_of_week"]= df["date"].dt.day_name()

In [ ]:
sales_by_day= df.groupby("day_of_week")["revenue"].sum()
sales_by_day

In [ ]:
days = [
    "Monday", "Tuesday", "Wednesday", 
    "Thursday","Friday", "Saturday","Sunday"
]

sales_by_day =sales_by_day.reindex(days)
print(sales_by_day)

In [ ]:
best_day=sales_by_day.idxmax()
best_sales= sales_by_day.max()

print(best_day)
print(best_sales)

Question (8), Find the top 5 bestselling pizzas

In [ ]:
df = df.merge(pizzas_types, on ="pizza_type_id")
df

In [ ]:
top_5_pizza = (
    df.groupby("name")["quantity"].sum()
    .sort_values(ascending=False)
    .head(5)
)

print(top_5_pizza)

Question (9), Find the sales made in each month. Any trend noticeable

In [ ]:
df["month"] = df["date"].dt.month_name()

In [ ]:
months= [
    "Jan","Feb","March", "Apr", 
    "May", "Jun", "July", "Aug",
    "Sep","Oct","Nov", "Deceb"
]

In [ ]:
monthly_sale= (
    df.groupby("month")["revenue"]
    .sum()
    .reindex(months)
)

print(monthly_sale)

Question (10), Are there pizza types that are not doing well on the menue

In [ ]:
low_selling_pizza = (
    df.groupby("name")["quantity"].sum()
    .sort_values(ascending= True)
)
print(low_selling_pizza.head(10))